# Generated by Django 4.2.3 on 2023-07-29 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=100)),
                ('saldo_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono_semanal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobrador', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semanas_atrasado', models.IntegerField()),
                ('saldo_vencido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
