# Generated by Django 4.2.3 on 2023-08-04 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='fecha_captura',
            field=models.DateField(),
        ),
    ]
